name: map_demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  bloc: ^8.1.1
  dio: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.4
  http: ^0.13.5
  im_stepper: ^1.0.1+1
  provider: ^6.0.5
  timelines: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
